version: "3.9"
services:
mongodb:
    image: mongo:4.4.6 1
    container name: meu-mongo
    networks:
        - compose-bridge
        
alurabooks:
    image: aluradocker/alura-books:1.0
    container name: alurabooks
    networks:
        - compose-bridge
    ports:
        - 3000:3000
        
networks:
    compose-bridge:
        driver: bridge

        
